"""Repository workspace package."""

from arkui_agent.repository.symbol_merge import (
    CanonicalSymbolGroup, SymbolMergeConflict, SymbolObservation,
    canonicalize_symbol_groups, canonicalize_symbols,
)

from arkui_agent.repository.clangd import (
    ClangdProtocolError,
    ClangdSemanticProvider,
    ClangdUnavailableError,
)
from arkui_agent.repository.dependency import (
    ChangeKind as RepositoryChangeKind,
    CompilationDatabaseProvider,
    CompileContext,
    CompileContextIdentity,
    CompileContextInventory,
    CompileContextProvider,
    ConfigurationInput,
    CoverageStatus as DependencyCoverageStatus,
    DependencyImpact,
    DependencyImpactAnalyzer,
    DependencyMetadataProvider,
    DependencyMetadataSnapshot,
    DependencyRecord,
    DiagnosticCode as DependencyDiagnosticCode,
    ImpactDiagnostic,
    ImpactStatus,
    MakeDepfileDependencyProvider,
    RepositoryChange,
    ReverseDependencyIndex,
    SemanticFileState,
    SemanticFingerprintInput,
    TranslationUnitIdentity,
    normalize_repository_changes,
)
from arkui_agent.repository.index import (
    SYMBOL_INDEX_FILENAME,
    SymbolIndex,
    SymbolIndexClosedError,
    SymbolIndexError,
    SymbolSemanticFacts,
    TestedSymbolMapping,
)
from arkui_agent.repository.model import (
    RepositoryFile,
    SourceLocation,
    SourceRange,
    Symbol,
    SymbolIdentity,
    SymbolKind,
    TestCase,
    TestFixture,
)
from arkui_agent.repository.scanner import (
    DEFAULT_EXCLUDED_DIRECTORIES,
    RepositoryFileType,
    RepositoryScanner,
    classify_repository_path,
)
from arkui_agent.repository.semantic import (
    SemanticProvider,
    SemanticProviderClosedError,
    SemanticProviderError,
)
from arkui_agent.repository.test_discovery import (
    ARKUI_FIXTURE_TEST_MACROS,
    RepositoryTestDiscoverer,
    TestDiscovery,
    TestDiscoveryError,
    TestMacroRecognizer,
)
from arkui_agent.repository.text_search import (
    RepositoryTextSearch,
    RepositoryTextSearchError,
    TextSearchBackendError,
    TextSearchMode,
    TextSearchQuery,
    TextSearchQueryError,
    TextSearchResult,
    TextSearchToolUnavailableError,
)
from arkui_agent.repository.workspace import (
    ARKUI_REPO_ROOT,
    RepositoryConfigurationError,
    RepositoryPathError,
    RepositoryRootError,
    RepositoryWorkspace,
    RepositoryWorkspaceError,
)

__all__ = [
    "CanonicalSymbolGroup", "canonicalize_symbol_groups",
    "SymbolMergeConflict",
    "SymbolObservation",
    "canonicalize_symbols",
    "ARKUI_REPO_ROOT",
    "ARKUI_FIXTURE_TEST_MACROS",
    "ClangdProtocolError",
    "ClangdSemanticProvider",
    "ClangdUnavailableError",
    "CompilationDatabaseProvider",
    "CompileContext",
    "CompileContextIdentity",
    "CompileContextInventory",
    "CompileContextProvider",
    "ConfigurationInput",
    "DEFAULT_EXCLUDED_DIRECTORIES",
    "DependencyCoverageStatus",
    "DependencyDiagnosticCode",
    "DependencyImpact",
    "DependencyImpactAnalyzer",
    "DependencyMetadataProvider",
    "DependencyMetadataSnapshot",
    "DependencyRecord",
    "RepositoryConfigurationError",
    "RepositoryChange",
    "RepositoryChangeKind",
    "RepositoryFile",
    "RepositoryFileType",
    "RepositoryPathError",
    "RepositoryRootError",
    "RepositoryScanner",
    "RepositoryTestDiscoverer",
    "RepositoryTextSearch",
    "RepositoryTextSearchError",
    "RepositoryWorkspace",
    "RepositoryWorkspaceError",
    "ReverseDependencyIndex",
    "SemanticProvider",
    "SemanticProviderClosedError",
    "SemanticProviderError",
    "SemanticFileState",
    "SemanticFingerprintInput",
    "SYMBOL_INDEX_FILENAME",
    "SourceLocation",
    "SourceRange",
    "Symbol",
    "SymbolIdentity",
    "SymbolIndex",
    "SymbolIndexClosedError",
    "SymbolIndexError",
    "SymbolKind",
    "SymbolSemanticFacts",
    "TestCase",
    "TestDiscovery",
    "TestDiscoveryError",
    "TestFixture",
    "TestMacroRecognizer",
    "TextSearchBackendError",
    "TextSearchMode",
    "TextSearchQuery",
    "TextSearchQueryError",
    "TextSearchResult",
    "TextSearchToolUnavailableError",
    "TranslationUnitIdentity",
    "TestedSymbolMapping",
    "classify_repository_path",
    "ImpactDiagnostic",
    "ImpactStatus",
    "MakeDepfileDependencyProvider",
    "normalize_repository_changes",
]
